#ifndef __PROJECT_EULER_PROBLEM044_H__
#define __PROJECT_EULER_PROBLEM044_H__
/*
 * ProjectEuler/include/c/ProjectEuler/Problem044.h
 *
 * Pentagon numbers
 * ================
 * Published on Friday, 23rd May 2003, 06:00 pm
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten
 * pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... It can be
 * seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 =
 * 48, is not pentagonal. Find the pair of pentagonal numbers, Pj and Pk, for
 * which their sum and difference are pentagonal and D = |Pk  Pj| is minimised;
 * what is the value of D?
 */

#  ifdef __cplusplus
extern "C" {
#  endif

#  ifdef __cplusplus
}
#  endif

#endif  /* __PROJECT_EULER_PROBLEM044_H__ */
