/*
 * ProjectEuler/src/c/Problem044.c
 *
 * Pentagon numbers
 * ================
 * Published on Friday, 23rd May 2003, 06:00 pm
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten
 * pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ... It can be
 * seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70  22 =
 * 48, is not pentagonal. Find the pair of pentagonal numbers, Pj and Pk, for
 * which their sum and difference are pentagonal and D = |Pk  Pj| is minimised;
 * what is the value of D?
 */
 
#include <stdio.h>
#include "ProjectEuler/ProjectEuler.h"
#include "ProjectEuler/Problem044.h"


int main(int argc, char** argv) {

    return 0;
}