/*
 * ProjectEuler/src/c/Problem045.c
 *
 * Triangular, pentagonal, and hexagonal
 * =====================================
 * Published on Friday, 6th June 2003, 06:00 pm
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:   Triangle   Tn=n(n+1)/2   1, 3, 6, 10, 15, ...   Pentagonal
 * Pn=n(3n1)/2   1, 5, 12, 22, 35, ...   Hexagonal   Hn=n(2n1)   1, 6, 15, 28,
 * 45, ...   It can be verified that T285 = P165 = H143 = 40755. Find the next
 * triangle number that is also pentagonal and hexagonal.
 */
 
#include <stdio.h>
#include "ProjectEuler/ProjectEuler.h"
#include "ProjectEuler/Problem045.h"


int main(int argc, char** argv) {

    return 0;
}